In [8]:
import numpy as np

In [9]:
train_spd_X_path = '/home/ubuntu/xuhao/data/spd_train_npy_set/train_spd_X.npy'
train_spd_Y_path = '/home/ubuntu/xuhao/data/spd_train_npy_set/train_spd_Y.npy'
test_spd_X_path = '/home/ubuntu/xuhao/data/spd_test_npy_set/test_spd_X.npy'
test_spd_Y_path = '/home/ubuntu/xuhao/data/spd_test_npy_set/test_spd_Y.npy'

In [10]:
train_spd_X = np.load(train_spd_X_path)
train_spd_Y = np.load(train_spd_Y_path)
test_spd_X = np.load(test_spd_X_path)
test_spd_Y = np.load(test_spd_Y_path)

In [12]:
data1 = train_spd_Y
data2 = test_spd_Y
print('np.unique(data)\n',np.unique(data1)) # unique返回的是已排序数组
print('np.unique(data)\n',np.unique(data2))
for i in np.unique(data1):
    print(np.sum(data1==i)) 
for i in np.unique(data2):
    print(np.sum(data2==i)) 

np.unique(data)
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
np.unique(data)
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
972
968
998
983
984
987
969
972
999
994
872
243
242
249
246
246
247
242
243
250
248
218


In [13]:
train_X_path = '/home/ubuntu/xuhao/data/train_npy_set/train_X.npy'
train_Y_path = '/home/ubuntu/xuhao/data/train_npy_set/train_Y.npy'
test_X_path = '/home/ubuntu/xuhao/data/test_npy_set/test_X.npy'
test_Y_path = '/home/ubuntu/xuhao/data/test_npy_set/test_Y.npy'

In [14]:
train_X = np.load(train_X_path)
train_Y = np.load(train_Y_path)
test_X = np.load(test_X_path)
test_Y = np.load(test_Y_path)

In [16]:
data1 = train_Y
data2 = test_Y
print('np.unique(data)\n',np.unique(data1)) # unique返回的是已排序数组
print('np.unique(data)\n',np.unique(data2))
for i in np.unique(data1):
    print(np.sum(data1==i)) 
for i in np.unique(data2):
    print(np.sum(data2==i)) 

np.unique(data)
 [ 0  1  2  3  4  5  6  7  8  9 10]
np.unique(data)
 [ 0  1  2  3  4  5  6  7  8  9 10]
194193
193567
199553
196352
196744
197252
193516
194391
203235
196432
174443
48560
48395
49897
49063
49221
49340
48389
48595
50762
49083
43546
