In [3]:
import numpy as np

In [1]:
def dealSPD(A):
    n = A.shape[0]
    B = np.zeros(shape=(1, n*(n+1)//2))
    j = 0
    for i in range(0,n):
        B[:,j:j+n-i] = A[i,i:n]
        j = j + n -i
    return B

In [5]:
A = np.array(A)

In [6]:
A

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [7]:
B = []
for i in range(0,3):
    for j in range(i,3):
        B.append(A[i,j])

In [8]:
B

[1, 2, 3, 3, 4, 5]

In [39]:
B

array([[1., 2., 3., 3., 4., 5.]])

In [36]:
B[:,1]

array([0.])

In [20]:
A[i,i:n]

array([3, 4])

In [23]:
B[j:j+n-i]

array([], shape=(0, 3), dtype=float64)

In [26]:
B

array([[0., 0., 0., 0., 0., 0.]])