In [275]:
import numpy as np
import math
from scipy.linalg import expm,logm
import sys

In [144]:
np.isnan(1)

False

In [145]:
## 计算黎曼距离
def riemann_distance(X,Y,gtype):
    if gtype == 'A':
        tmpEig = geneig(X,Y)
        tmp_dis = sum(mylog(tmpEig) ** 2)
    elif gtype == 'S':
        t = mylog(np.linalg.det(0.5 * (X + Y))) - 0.5 * (mylog(np.linalg.det(X))) + mylog(np.linalg.det(Y))
        if t == np.inf or np.isnan(t):
            eigX = np.linalg.eig(X)
            eigX = np.maximum(eigX,eps)
            eigY = np.linalg.eig(Y);
            eigY = np.maximum(eigY,eps)

            t = np.real(sum(mylog(np.linalg.eig(0.5*(X+Y))))) - 0.5 * (np.real(sum(mylog(eigX)))) + np.real(sum(mylog(eigY)))

        tmp_dis = t;
    elif gtype == 'J':
        tmp_dis = 0.5 * (np.dot(np.linalg.inv(Y),X)).trace() + 0.5 * (np.dot(np.linalg.inv(X),Y)).trace() - X.shape[0]
    elif gtype == 'L':
        tmp_dis = np.linalg.norm((logm(X) - logm(Y)),ord='fro') ** 2
    
    if tmp_dis <= 1e-15:
        dis = 0
    else:
        dis = np.sqrt(tmp_dis);
    return dis

## 计算广义特征值
def geneig(X,Y):
    w,v = np.linalg.eig(np.dot(np.linalg.inv(Y),X))
    return w

## 计算可能出现负数的对数函数
def mylog(X):
    CX = X + 0j
    return np.log(CX)

In [232]:
A = [[2,3],[4,5]]

In [233]:
np.power(A,1/2)

array([[1.41421356, 1.73205081],
       [2.        , 2.23606798]])

In [235]:
np.linalg.matrix_power(A,2)

array([[16, 21],
       [28, 37]])

In [236]:
import numpy.matlib

In [237]:
A = numpy.matlib.matrix(A)

In [238]:
A

matrix([[2, 3],
        [4, 5]])

In [279]:
eig_val, eig_vec = np.linalg.eig(A) #特征分解

def mysqrt(X):
    xlen = len(X)
    sqrt_X = np.copy(X) + 0j
    for i in range(xlen):
        sqrt_X[i] = X[i] ** 0.5
    return sqrt_X
        

# eig_diag = np.diag((eig_val**0.5)) #特征值开方取倒数对角化
eig_diag = np.diag(mysqrt(eig_val))
B = np.dot(np.dot(eig_vec, eig_diag), np.linalg.inv(eig_vec)) #inv为求逆

/home/xuhao/miniconda3/envs/grdenv/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in double_scalars
  import sys


In [280]:
(-0.27491722) ** 0.5

(3.210567668330642e-17+0.5243254905113808j)

In [285]:
eig_val = eig_val + 0j
eig_val[0] = (-0.27491722) ** 0.5
eig_val

array([3.21056767e-17+0.52432549j, 7.27491722e+00+0.j        ])

In [282]:
mysqrt(eig_val)

/home/xuhao/miniconda3/envs/grdenv/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in double_scalars
  import sys


array([       nan+0.j, 2.69720545+0.j])

In [260]:
cmath.sqrt(eig_val+0j)

TypeError: only length-1 arrays can be converted to Python scalars

TypeError: only length-1 arrays can be converted to Python scalars

In [256]:
a = -1
(a) ** 0.5

(6.123233995736766e-17+1j)

In [255]:
(6.123233995736766e-17+1j) * (6.123233995736766e-17+1j)

(-1+1.2246467991473532e-16j)